//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.14 at 01:26:02 PM PDT 
//


package com.lithium.integrations;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lithium.integrations package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class AvatarObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lithium.integrations
     * 
     */
    public AvatarObjectFactory() {
    }

    /**
     * Create an instance of {@link Avatar }
     * 
     */
    public Avatar createResponse() {
        return new Avatar();
    }

    /**
     * Create an instance of {@link Avatar.Image }
     * 
     */
    public Avatar.Image createResponseImage() {
        return new Avatar.Image();
    }

    /**
     * Create an instance of {@link Avatar.Image.Url }
     * 
     */
    public Avatar.Image.Url createResponseImageUrl() {
        return new Avatar.Image.Url();
    }

    /**
     * Create an instance of {@link Avatar.Image.Width }
     * 
     */
    public Avatar.Image.Width createResponseImageWidth() {
        return new Avatar.Image.Width();
    }

    /**
     * Create an instance of {@link Avatar.Image.Height }
     * 
     */
    public Avatar.Image.Height createResponseImageHeight() {
        return new Avatar.Image.Height();
    }

}
