//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.14 at 12:30:51 PM PDT 
//


package com.lithium.integrations;

import javax.xml.bind.annotation.XmlRegistry;

import com.lithium.integrations.model.Response;
import com.lithium.integrations.model.Response.User;
import com.lithium.integrations.model.Response.User.Anonymous;
import com.lithium.integrations.model.Response.User.AverageMessageRating;
import com.lithium.integrations.model.Response.User.AverageRating;
import com.lithium.integrations.model.Response.User.Deleted;
import com.lithium.integrations.model.Response.User.Id;
import com.lithium.integrations.model.Response.User.LastVisitTime;
import com.lithium.integrations.model.Response.User.Login;
import com.lithium.integrations.model.Response.User.Profiles;
import com.lithium.integrations.model.Response.User.Registered;
import com.lithium.integrations.model.Response.User.RegistrationTime;
import com.lithium.integrations.model.Response.User.Profiles.Profile;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lithium.integrations.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lithium.integrations.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Response.User }
     * 
     */
    public Response.User createResponseUser() {
        return new Response.User();
    }

    /**
     * Create an instance of {@link Response.User.Profiles }
     * 
     */
    public Response.User.Profiles createResponseUserProfiles() {
        return new Response.User.Profiles();
    }

    /**
     * Create an instance of {@link Response.User.AverageMessageRating }
     * 
     */
    public Response.User.AverageMessageRating createResponseUserAverageMessageRating() {
        return new Response.User.AverageMessageRating();
    }

    /**
     * Create an instance of {@link Response.User.Login }
     * 
     */
    public Response.User.Login createResponseUserLogin() {
        return new Response.User.Login();
    }

    /**
     * Create an instance of {@link Response.User.Anonymous }
     * 
     */
    public Response.User.Anonymous createResponseUserAnonymous() {
        return new Response.User.Anonymous();
    }

    /**
     * Create an instance of {@link Response.User.AverageRating }
     * 
     */
    public Response.User.AverageRating createResponseUserAverageRating() {
        return new Response.User.AverageRating();
    }

    /**
     * Create an instance of {@link Response.User.Deleted }
     * 
     */
    public Response.User.Deleted createResponseUserDeleted() {
        return new Response.User.Deleted();
    }

    /**
     * Create an instance of {@link Response.User.Registered }
     * 
     */
    public Response.User.Registered createResponseUserRegistered() {
        return new Response.User.Registered();
    }

    /**
     * Create an instance of {@link Response.User.Id }
     * 
     */
    public Response.User.Id createResponseUserId() {
        return new Response.User.Id();
    }

    /**
     * Create an instance of {@link Response.User.LastVisitTime }
     * 
     */
    public Response.User.LastVisitTime createResponseUserLastVisitTime() {
        return new Response.User.LastVisitTime();
    }

    /**
     * Create an instance of {@link Response.User.RegistrationTime }
     * 
     */
    public Response.User.RegistrationTime createResponseUserRegistrationTime() {
        return new Response.User.RegistrationTime();
    }

    /**
     * Create an instance of {@link Response.User.Profiles.Profile }
     * 
     */
    public Response.User.Profiles.Profile createResponseUserProfilesProfile() {
        return new Response.User.Profiles.Profile();
    }

}
