//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.19 at 11:15:05 AM PDT 
//


package com.lithium.integrations;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lithium.integrations package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class RankingsObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lithium.integrations
     * 
     */
    public RankingsObjectFactory() {
    }

    /**
     * Create an instance of {@link Rankings }
     * 
     */
    public Rankings createResponse() {
        return new Rankings();
    }

    /**
     * Create an instance of {@link Rankings.Ranking }
     * 
     */
    public Rankings.Ranking createResponseRanking() {
        return new Rankings.Ranking();
    }

    /**
     * Create an instance of {@link Rankings.Ranking.Display }
     * 
     */
    public Rankings.Ranking.Display createResponseRankingDisplay() {
        return new Rankings.Ranking.Display();
    }

    /**
     * Create an instance of {@link Rankings.Ranking.Display.LeftImage }
     * 
     */
    public Rankings.Ranking.Display.LeftImage createResponseRankingDisplayLeftImage() {
        return new Rankings.Ranking.Display.LeftImage();
    }

    /**
     * Create an instance of {@link Rankings.Ranking.Name }
     * 
     */
    public Rankings.Ranking.Name createResponseRankingName() {
        return new Rankings.Ranking.Name();
    }

    /**
     * Create an instance of {@link Rankings.Ranking.Id }
     * 
     */
    public Rankings.Ranking.Id createResponseRankingId() {
        return new Rankings.Ranking.Id();
    }

    /**
     * Create an instance of {@link Rankings.Ranking.Display.RightImage }
     * 
     */
    public Rankings.Ranking.Display.RightImage createResponseRankingDisplayRightImage() {
        return new Rankings.Ranking.Display.RightImage();
    }

    /**
     * Create an instance of {@link Rankings.Ranking.Display.ThreadImage }
     * 
     */
    public Rankings.Ranking.Display.ThreadImage createResponseRankingDisplayThreadImage() {
        return new Rankings.Ranking.Display.ThreadImage();
    }

    /**
     * Create an instance of {@link Rankings.Ranking.Display.Color }
     * 
     */
    public Rankings.Ranking.Display.Color createResponseRankingDisplayColor() {
        return new Rankings.Ranking.Display.Color();
    }

    /**
     * Create an instance of {@link Rankings.Ranking.Display.Bold }
     * 
     */
    public Rankings.Ranking.Display.Bold createResponseRankingDisplayBold() {
        return new Rankings.Ranking.Display.Bold();
    }

    /**
     * Create an instance of {@link Rankings.Ranking.Display.LeftImage.Height }
     * 
     */
    public Rankings.Ranking.Display.LeftImage.Height createResponseRankingDisplayLeftImageHeight() {
        return new Rankings.Ranking.Display.LeftImage.Height();
    }

    /**
     * Create an instance of {@link Rankings.Ranking.Display.LeftImage.Width }
     * 
     */
    public Rankings.Ranking.Display.LeftImage.Width createResponseRankingDisplayLeftImageWidth() {
        return new Rankings.Ranking.Display.LeftImage.Width();
    }

    /**
     * Create an instance of {@link Rankings.Ranking.Display.LeftImage.Url }
     * 
     */
    public Rankings.Ranking.Display.LeftImage.Url createResponseRankingDisplayLeftImageUrl() {
        return new Rankings.Ranking.Display.LeftImage.Url();
    }

}
