//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.18 at 07:28:45 PM PDT 
//


package com.lithium.integrations;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lithium.integrations package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class RecentTopicsObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lithium.integrations
     * 
     */
    public RecentTopicsObjectFactory() {
    }

    /**
     * Create an instance of {@link RecentTopics }
     * 
     */
    public RecentTopics createResponse() {
        return new RecentTopics();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages }
     * 
     */
    public RecentTopics.Messages createResponseMessages() {
        return new RecentTopics.Messages();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message }
     * 
     */
    public RecentTopics.Messages.Message createResponseMessagesMessage() {
        return new RecentTopics.Messages.Message();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Views }
     * 
     */
    public RecentTopics.Messages.Message.Views createResponseMessagesMessageViews() {
        return new RecentTopics.Messages.Message.Views();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Author }
     * 
     */
    public RecentTopics.Messages.Message.Author createResponseMessagesMessageAuthor() {
        return new RecentTopics.Messages.Message.Author();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Labels }
     * 
     */
    public RecentTopics.Messages.Message.Labels createResponseMessagesMessageLabels() {
        return new RecentTopics.Messages.Message.Labels();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Labels.Label }
     * 
     */
    public RecentTopics.Messages.Message.Labels.Label createResponseMessagesMessageLabelsLabel() {
        return new RecentTopics.Messages.Message.Labels.Label();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Kudos }
     * 
     */
    public RecentTopics.Messages.Message.Kudos createResponseMessagesMessageKudos() {
        return new RecentTopics.Messages.Message.Kudos();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.LastEditAuthor }
     * 
     */
    public RecentTopics.Messages.Message.LastEditAuthor createResponseMessagesMessageLastEditAuthor() {
        return new RecentTopics.Messages.Message.LastEditAuthor();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.MessageRating }
     * 
     */
    public RecentTopics.Messages.Message.MessageRating createResponseMessagesMessageMessageRating() {
        return new RecentTopics.Messages.Message.MessageRating();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Subject }
     * 
     */
    public RecentTopics.Messages.Message.Subject createResponseMessagesMessageSubject() {
        return new RecentTopics.Messages.Message.Subject();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Id }
     * 
     */
    public RecentTopics.Messages.Message.Id createResponseMessagesMessageId() {
        return new RecentTopics.Messages.Message.Id();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.ReadOnly }
     * 
     */
    public RecentTopics.Messages.Message.ReadOnly createResponseMessagesMessageReadOnly() {
        return new RecentTopics.Messages.Message.ReadOnly();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Deleted }
     * 
     */
    public RecentTopics.Messages.Message.Deleted createResponseMessagesMessageDeleted() {
        return new RecentTopics.Messages.Message.Deleted();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Thread }
     * 
     */
    public RecentTopics.Messages.Message.Thread createResponseMessagesMessageThread() {
        return new RecentTopics.Messages.Message.Thread();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.PostTime }
     * 
     */
    public RecentTopics.Messages.Message.PostTime createResponseMessagesMessagePostTime() {
        return new RecentTopics.Messages.Message.PostTime();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.LastEditTime }
     * 
     */
    public RecentTopics.Messages.Message.LastEditTime createResponseMessagesMessageLastEditTime() {
        return new RecentTopics.Messages.Message.LastEditTime();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Board }
     * 
     */
    public RecentTopics.Messages.Message.Board createResponseMessagesMessageBoard() {
        return new RecentTopics.Messages.Message.Board();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Parent }
     * 
     */
    public RecentTopics.Messages.Message.Parent createResponseMessagesMessageParent() {
        return new RecentTopics.Messages.Message.Parent();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Teaser }
     * 
     */
    public RecentTopics.Messages.Message.Teaser createResponseMessagesMessageTeaser() {
        return new RecentTopics.Messages.Message.Teaser();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.BoardId }
     * 
     */
    public RecentTopics.Messages.Message.BoardId createResponseMessagesMessageBoardId() {
        return new RecentTopics.Messages.Message.BoardId();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Root }
     * 
     */
    public RecentTopics.Messages.Message.Root createResponseMessagesMessageRoot() {
        return new RecentTopics.Messages.Message.Root();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Views.Count }
     * 
     */
    public RecentTopics.Messages.Message.Views.Count createResponseMessagesMessageViewsCount() {
        return new RecentTopics.Messages.Message.Views.Count();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Author.Login }
     * 
     */
    public RecentTopics.Messages.Message.Author.Login createResponseMessagesMessageAuthorLogin() {
        return new RecentTopics.Messages.Message.Author.Login();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Labels.Label.Text }
     * 
     */
    public RecentTopics.Messages.Message.Labels.Label.Text createResponseMessagesMessageLabelsLabelText() {
        return new RecentTopics.Messages.Message.Labels.Label.Text();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Labels.Label.Id }
     * 
     */
    public RecentTopics.Messages.Message.Labels.Label.Id createResponseMessagesMessageLabelsLabelId() {
        return new RecentTopics.Messages.Message.Labels.Label.Id();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.Kudos.Count }
     * 
     */
    public RecentTopics.Messages.Message.Kudos.Count createResponseMessagesMessageKudosCount() {
        return new RecentTopics.Messages.Message.Kudos.Count();
    }

    /**
     * Create an instance of {@link RecentTopics.Messages.Message.LastEditAuthor.Login }
     * 
     */
    public RecentTopics.Messages.Message.LastEditAuthor.Login createResponseMessagesMessageLastEditAuthorLogin() {
        return new RecentTopics.Messages.Message.LastEditAuthor.Login();
    }

}
