//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.18 at 09:09:10 PM PDT 
//


package com.lithium.integrations;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lithium.integrations package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class TopicMessageObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lithium.integrations
     * 
     */
    public TopicMessageObjectFactory() {
    }

    /**
     * Create an instance of {@link TopicMessage }
     * 
     */
    public TopicMessage createResponse() {
        return new TopicMessage();
    }

    /**
     * Create an instance of {@link TopicMessage.Message }
     * 
     */
    public TopicMessage.Message createResponseMessage() {
        return new TopicMessage.Message();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Views }
     * 
     */
    public TopicMessage.Message.Views createResponseMessageViews() {
        return new TopicMessage.Message.Views();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Author }
     * 
     */
    public TopicMessage.Message.Author createResponseMessageAuthor() {
        return new TopicMessage.Message.Author();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Labels }
     * 
     */
    public TopicMessage.Message.Labels createResponseMessageLabels() {
        return new TopicMessage.Message.Labels();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Labels.Label }
     * 
     */
    public TopicMessage.Message.Labels.Label createResponseMessageLabelsLabel() {
        return new TopicMessage.Message.Labels.Label();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Kudos }
     * 
     */
    public TopicMessage.Message.Kudos createResponseMessageKudos() {
        return new TopicMessage.Message.Kudos();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.LastEditAuthor }
     * 
     */
    public TopicMessage.Message.LastEditAuthor createResponseMessageLastEditAuthor() {
        return new TopicMessage.Message.LastEditAuthor();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.MessageRating }
     * 
     */
    public TopicMessage.Message.MessageRating createResponseMessageMessageRating() {
        return new TopicMessage.Message.MessageRating();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Subject }
     * 
     */
    public TopicMessage.Message.Subject createResponseMessageSubject() {
        return new TopicMessage.Message.Subject();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Id }
     * 
     */
    public TopicMessage.Message.Id createResponseMessageId() {
        return new TopicMessage.Message.Id();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.ReadOnly }
     * 
     */
    public TopicMessage.Message.ReadOnly createResponseMessageReadOnly() {
        return new TopicMessage.Message.ReadOnly();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Deleted }
     * 
     */
    public TopicMessage.Message.Deleted createResponseMessageDeleted() {
        return new TopicMessage.Message.Deleted();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Body }
     * 
     */
    public TopicMessage.Message.Body createResponseMessageBody() {
        return new TopicMessage.Message.Body();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Thread }
     * 
     */
    public TopicMessage.Message.Thread createResponseMessageThread() {
        return new TopicMessage.Message.Thread();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.PostTime }
     * 
     */
    public TopicMessage.Message.PostTime createResponseMessagePostTime() {
        return new TopicMessage.Message.PostTime();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.LastEditTime }
     * 
     */
    public TopicMessage.Message.LastEditTime createResponseMessageLastEditTime() {
        return new TopicMessage.Message.LastEditTime();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Board }
     * 
     */
    public TopicMessage.Message.Board createResponseMessageBoard() {
        return new TopicMessage.Message.Board();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Parent }
     * 
     */
    public TopicMessage.Message.Parent createResponseMessageParent() {
        return new TopicMessage.Message.Parent();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Teaser }
     * 
     */
    public TopicMessage.Message.Teaser createResponseMessageTeaser() {
        return new TopicMessage.Message.Teaser();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.BoardId }
     * 
     */
    public TopicMessage.Message.BoardId createResponseMessageBoardId() {
        return new TopicMessage.Message.BoardId();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Root }
     * 
     */
    public TopicMessage.Message.Root createResponseMessageRoot() {
        return new TopicMessage.Message.Root();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Views.Count }
     * 
     */
    public TopicMessage.Message.Views.Count createResponseMessageViewsCount() {
        return new TopicMessage.Message.Views.Count();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Author.Login }
     * 
     */
    public TopicMessage.Message.Author.Login createResponseMessageAuthorLogin() {
        return new TopicMessage.Message.Author.Login();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Labels.Label.Text }
     * 
     */
    public TopicMessage.Message.Labels.Label.Text createResponseMessageLabelsLabelText() {
        return new TopicMessage.Message.Labels.Label.Text();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Labels.Label.Id }
     * 
     */
    public TopicMessage.Message.Labels.Label.Id createResponseMessageLabelsLabelId() {
        return new TopicMessage.Message.Labels.Label.Id();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.Kudos.Count }
     * 
     */
    public TopicMessage.Message.Kudos.Count createResponseMessageKudosCount() {
        return new TopicMessage.Message.Kudos.Count();
    }

    /**
     * Create an instance of {@link TopicMessage.Message.LastEditAuthor.Login }
     * 
     */
    public TopicMessage.Message.LastEditAuthor.Login createResponseMessageLastEditAuthorLogin() {
        return new TopicMessage.Message.LastEditAuthor.Login();
    }

}
